In [44]:
# Import dependencies
import pandas as pd
import gmaps
import requests

# Import the API key
from config import g_key

In [45]:
# Store the CSV I created earlier into a DataFrame
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Rikitea,PF,2021-12-05 13:42:37,-23.1203,-134.9692,75.09,76,77,7.92
1,1,Manbij,SY,2021-12-05 13:42:37,36.5281,37.9549,57.97,34,100,9.62
2,2,East London,ZA,2021-12-05 13:42:37,-33.0153,27.9116,72.54,94,75,17.27
3,3,Hamilton,US,2021-12-05 13:40:09,39.1834,-84.5333,38.25,70,90,1.99
4,4,Itarema,BR,2021-12-05 13:42:38,-2.9248,-39.9167,89.06,56,39,18.92

In [46]:
# Confirm the data types
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [47]:
# Configure gmaps to use my Google API key
gmaps.configure(api_key=g_key)

In [48]:
# Get the maximum temperature
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [49]:
%matplotlib inline

In [54]:
# Heatmap of temperature

# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]

# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [56]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [58]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [59]:
# Heatmap of wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [60]:
# Ask the customer to add a minimum and maximum temperature value
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [62]:
# Filter the dataset to find the cities that fit the criteria
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Rikitea,PF,2021-12-05 13:42:37,-23.1203,-134.9692,75.09,76,77,7.92
4,4,Itarema,BR,2021-12-05 13:42:38,-2.9248,-39.9167,89.06,56,39,18.92
7,7,Hermanus,ZA,2021-12-05 13:42:38,-34.4187,19.2345,75.90,89,85,12.28
9,9,Atuona,PF,2021-12-05 13:42:39,-9.8000,-139.0333,77.79,75,0,16.06
14,14,Luganville,VU,2021-12-05 13:42:39,-15.5333,167.1667,77.61,82,4,4.05
16,16,Matara,LK,2021-12-05 13:42:40,5.9485,80.5353,79.07,86,60,4.07
18,18,Pochutla,MX,2021-12-05 13:42:40,15.7432,-96.4661,75.02,43,0,1.79
23,23,Praia,CV,2021-12-05 13:42:41,14.9215,-23.5087,79.34,57,0,23.02
24,24,Nouadhibou,MR,2021-12-05 13:42:42,20.9310,-17.0347,75.18,33,40,10.36
27,27,Grand Gaube,MU,2021-12-05 13:42:43,-20.0064,57.6608,84.60,66,22,7.00

In [63]:
preferred_cities_df.count()

City_ID       175
City          175
Country       174
Date          175
Lat           175
Lng           175
Max Temp      175
Humidity      175
Cloudiness    175
Wind Speed    175
dtype: int64

In [64]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

           City Country  Max Temp      Lat       Lng Hotel Name
0       Rikitea      PF     75.09 -23.1203 -134.9692
4       Itarema      BR     89.06  -2.9248  -39.9167
7      Hermanus      ZA     75.90 -34.4187   19.2345
9        Atuona      PF     77.79  -9.8000 -139.0333
14   Luganville      VU     77.61 -15.5333  167.1667
16       Matara      LK     79.07   5.9485   80.5353
18     Pochutla      MX     75.02  15.7432  -96.4661
23        Praia      CV     79.34  14.9215  -23.5087
24   Nouadhibou      MR     75.18  20.9310  -17.0347
27  Grand Gaube      MU     84.60 -20.0064   57.6608

In [67]:
# Set parameters to search for a hotel
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# Iterate through the DataFrame
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [81]:
hotel_df.sample(50)

,City,Country,Max Temp,Lat,Lng,Hotel Name
223,Bako,ET,80.69,5.7833,36.5667,Goh Hotel
24,Nouadhibou,MR,75.18,20.9310,-17.0347,El Medina
37,Mahebourg,MU,84.49,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
4,Itarema,BR,89.06,-2.9248,-39.9167,"Sea Lounge! Bar, Club & Restaurant"
268,Ambon,ID,78.94,-3.6954,128.1814,Swiss-Belhotel Ambon
0,Rikitea,PF,75.09,-23.1203,-134.9692,People ThankYou
338,Inirida,CO,83.70,3.8653,-67.9239,Fuente del Guania Hotel de Lujo
270,Grand-Santi,GF,85.77,4.2500,-54.3833,Hotel La Villa Couacou
385,Luanda,AO,86.00,-8.8368,13.2343,Hotel Fórum
355,Beira,MZ,89.69,-19.8436,34.8389,Beira Terrace Hotel
134,Georgetown,MY,82.89,5.4112,100.3354,Cititel Penang
153,Padre Bernardo,BR,80.69,-15.3500,-48.5000,
451,Oranjestad,AW,80.55,12.5240,-70.0270,Divi Village Golf & Beach Resort
191,Warri,NG,86.38,5.5167,5.7500,BON Hotel Delta
373,Acapulco,MX,75.02,16.8634,-99.8901,HS Hotsson Smart Acapulco
9,Atuona,PF,77.79,-9.8000,-139.0333,Villa Enata
259,Tual,ID,83.37,-5.6667,132.7500,Grand Vilia Hotel
157,Rawson,AR,75.02,-43.3002,-65.1023,Hosteria Sampedro
59,Sao Felix Do Xingu,BR,77.13,-6.6447,-51.9950,Rio Xingu Camping
14,Luganville,VU,77.61,-15.5333,167.1667,The Espiritu Hotel
49,Pio Ix,BR,88.72,-6.8375,-40.5792,Hotel Central
61,Salalah,OM,82.49,17.0151,54.0924,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
430,Saint-Pierre,RE,82.29,-21.3393,55.4781,Lindsey Hôtel
133,Sakassou,CI,89.44,7.4546,-5.2926,Parents de Damienne
557,Carnarvon,AU,78.87,-24.8667,113.6333,Hospitality Carnarvon
155,Cuite,BR,87.37,-6.4836,-36.1536,Hotel Planalto
233,Port Hedland,AU,89.65,-20.3167,118.5667,The Esplanade Hotel
89,Bengkulu,ID,75.58,-3.8004,102.2655,Grage Hotel Bengkulu
566,Bonthe,SL,89.11,7.5264,-12.5050,Bonthe Holiday Village
221,Alta Floresta,BR,76.82,-9.8756,-56.0861,Floresta Amazonica Hotel
80,Ormara,PK,77.07,25.2088,64.6357,Crystal Beach and Camping Resort Ormara
265,Sola,VU,80.08,-13.8833,167.5500,Leumerus Bungalows
69,Shakawe,BW,81.61,-18.3667,21.8500,Ditlhapi Guest House
372,Weligama,LK,79.41,5.9667,80.4167,Weligama Bay Resort
152,Kerema,PG,77.81,-7.9631,145.7785,Frena Lodge
393,Sinnamary,GF,79.16,5.3833,-52.9500,ALETHEIA Appartement Sinnamary
447,Mackay,AU,78.78,-21.1500,149.2000,International Lodge Motel
411,Manokwari,ID,79.14,-0.8667,134.0833,Swiss Belhotel Manokwari
408,Kloulklubed,PW,83.48,7.0419,134.2556,Storyboard Beach Resort
93,Arraial Do Cabo,BR,82.36,-22.9661,-42.0278,Pousada Porto Praia
487,Puerto Narino,CO,75.15,-3.7703,-70.3831,Eware Refugio Amazonico
23,Praia,CV,79.34,14.9215,-23.5087,LT Aparthotel
182,Viedma,AR,75.92,-40.8135,-62.9967,Hotel Cristal
409,Nuevitas,CU,79.34,21.5453,-77.2644,Hotel Caonaba
547,Saint-Georges,GD,85.68,12.0564,-61.7485,Radisson Grenada Beach Resort
209,Sambava,MG,81.48,-14.2667,50.1667,Melrose
236,Merauke,ID,81.03,-8.4667,140.3333,
31,Kulhudhuffushi,MV,82.06,6.6221,73.0700,Haajy Guest House 1
57,Morant Bay,JM,80.62,17.8815,-76.4093,Whispering Bamboo Cove Resort
473,Manggar,ID,78.06,-2.8833,108.2667,Guest Hotel

In [82]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data
fig

Figure(layout=FigureLayout(height='420px'))